version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hr-scanning-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: hr_scanning_dev
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password_dev
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - '5433:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - hr-scanning-dev
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U hr_user -d hr_scanning_dev']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=8
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=8
      -c max_parallel_maintenance_workers=4

volumes:
  postgres_dev_data:
    driver: local

networks:
  hr-scanning-dev:
    driver: bridge
    name: hr-scanning-dev
